import Head from 'next/head'
import Link from 'next/link'
import { useAuthContext } from '../src/contexts/authContext';

import dynamic from 'next/dynamic'

const LoginForm = dynamic(() => import('../src/components/LoginForm'), {
  ssr: false,
})

export default function Home() {
  const { token, logout } = useAuthContext();

  return (
    <div >
      <Head>
        <title>Distributed app example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Login page
        </h1>
        {token ? (
          <div>
            <h1>You are logged in</h1>
            <p>If you wish to navigate to the landing page</p>
            <Link href="http://localhost:3000">
              <a>Click here</a>
            </Link>
            <button onClick={() => logout()}>Logout</button>
          </div>
        ) : <LoginForm />}
      </main>
    </div>
  )
}
