import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Distributed app example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the distributed app example
        </h1>

        <h2>
          This the main host Next.JS App running on Port 3000
        </h2>
        <p>
          This App is in charge of redirecting the user to the different apps.
        </p>

        <p className={styles.description}>
          This example is a distributed app that uses Next.js multi zones to handle multiple frontend projects.
          It also connects to multiple backend services linked via an API gateway.
        </p>

        <h2>
          Here is a list of the available pages:
        </h2>
        <ul>
          <li>
            <Link href="/">
              <a>Home (Root path ={'>'} This page)</a>
            </Link>
          </li>
          <li>
            <Link href="/auth">
              <a>Auth (/Auth)</a>
            </Link>
          </li>
          <li>
            <Link href="/products">
              <a>Products (/products)</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}
